### ISSUE TITLE
Allow accessing of field on pipe

### ISSUE THREAD

**Issue by rnwst** [jgm/doctemplates#30]
See jgm/pandoc#10757. I have a variable defined in frontmatter as follows:
```yaml
list:
  - id: 1
    name: Geoff
  - id: 2
    name: Alex
```
I have tried accessing the `name` of the last element in `list` like this:
```
$list/last.name$
```
However, this throws an error when running pandoc with this template:
```
unexpected "."
expecting "/", "(", ":", "[" or "$"
```
